# Copyright (c) Meta Platforms, Inc. and affiliates.
# Licensed under the license found in the LICENSE file in the root directory.
"""Gate 0d: localise where decision information is lost.

The architecture and dynamics checkpoints are frozen.  One shared candidate
bank is scored through:

 A. simulator truth;
 B. true trajectory -> encoder -> existing reward/termination readout;
 C. predicted latent trajectory -> existing reward/termination readout;
 D. predicted latent trajectory -> task-sufficient diagnostic head.

The same comparisons are repeated on every candidate population generated by
the existing reward-head CEM planner.  Diagnostic heads are the only fitted
components; they never update the encoder, transition, or existing readout.
"""

import argparse
import json
from pathlib import Path

import torch
import yaml
from torch import nn
from torch.utils.data import DataLoader
from tensordict import TensorDict

from benchmarl.environments import VmasTask
from examples.world_model.cem import CEMConfig, cem_plan
from examples.world_model.dataset import OfflineSequences
from examples.world_model.model_input import compose_frames, entity_frame
from examples.world_model.models import mlp
from examples.world_model.mpc import action_bounds, task_outcome, unpack_actions
from examples.world_model.plan_ranking import spearman
from examples.world_model.snapshot_restore import (
    agent_observations,
    broadcast_state,
    restore_state,
)
from examples.world_model.train import block_reward, load_model


KINDS = ("independent", "joint", "relational")
INPUTS = ("observation", "history", "physical")
REGIMES = ("correlated", "independent")
REGRESSION_NAMES = (
    "progress",
    "ball_clearance",
    "ball_x",
    "ball_y",
    "collision_cost",
)


def write_json(path, value):
    path.write_text(json.dumps(value, indent=2, allow_nan=False) + "\n")


def tree_map(value, function):
    if isinstance(value, dict):
        return {key: tree_map(item, function) for key, item in value.items()}
    return function(value) if torch.is_tensor(value) else value


def take_snapshot(snapshot, indices, device):
    indices = indices.to(snapshot["steps"].device)
    return tree_map(snapshot, lambda value: value.index_select(0, indices).to(device))


def ball_clearance(position):
    """Signed clearance from Buzz Wire's ball to its rectangular wire."""
    horizontal = 0.125 - position[..., 0].abs() - 0.03
    vertical = 1.0 - position[..., 1].abs() - 0.03
    return torch.minimum(horizontal, vertical)


@torch.no_grad()
def rollout_truth(task, snapshot, candidates, action_block, device):
    """Roll one shared candidate bank and retain physical/observation traces."""
    roots, count, horizon, plan_dim = candidates.shape
    primitive = unpack_actions(candidates.to(device), action_block)
    agents = 2
    action_dim = primitive.shape[-1] // agents
    primitive = primitive.reshape(roots * count, horizon * action_block, agents, action_dim)

    env = task.get_env_fun(roots * count, True, 0, device)()
    env.reset()
    broadcast_state(env, snapshot, source_indices=torch.arange(roots, device=device).repeat_interleave(count))
    scenario = env._env.scenario
    outcome = task_outcome("vmas/buzz_wire")
    td = TensorDict({}, batch_size=[roots * count], device=device)
    live = ~env._env.done()
    total = torch.zeros(roots * count, device=device)
    block_rewards = []
    block_collisions = []
    live_starts = []

    frozen_obs = agent_observations(env).clone()
    frozen_entities = entity_frame(env).clone()
    frozen_ball = scenario.ball.state.pos.clone()
    frozen_goal = scenario.goal.state.pos.clone()
    observations = [frozen_obs.cpu()]
    entities = [frozen_entities.cpu()]
    ball_positions = [frozen_ball.cpu()]
    goal_positions = [frozen_goal.cpu()]
    distances = [torch.linalg.vector_norm(frozen_ball - frozen_goal, dim=-1).cpu()]
    clearances = [ball_clearance(frozen_ball).cpu()]

    for block in range(horizon):
        live_starts.append(live.cpu())
        reward_sum = torch.zeros_like(total)
        collided = torch.zeros_like(live)
        for offset in range(action_block):
            step = block * action_block + offset
            td.set(("agents", "action"), primitive[:, step])
            td = env.step(td)["next"]
            reward = td["agents", "reward"].sum(dim=1).squeeze(-1)
            reward_sum += reward.masked_fill(~live, 0)
            total += reward.masked_fill(~live, 0)
            _success, crash, _distance = outcome(env)
            collided |= live & crash

            current_obs = agent_observations(env)
            current_entities = entity_frame(env)
            current_ball = scenario.ball.state.pos
            current_goal = scenario.goal.state.pos
            frozen_obs = torch.where(live[:, None, None], current_obs, frozen_obs)
            frozen_entities = torch.where(live[:, None], current_entities, frozen_entities)
            frozen_ball = torch.where(live[:, None], current_ball, frozen_ball)
            frozen_goal = torch.where(live[:, None], current_goal, frozen_goal)
            live = live & ~td["done"].squeeze(-1)

        block_rewards.append(reward_sum.cpu())
        block_collisions.append(collided.cpu())
        observations.append(frozen_obs.cpu())
        entities.append(frozen_entities.cpu())
        ball_positions.append(frozen_ball.cpu())
        goal_positions.append(frozen_goal.cpu())
        distances.append(
            torch.linalg.vector_norm(frozen_ball - frozen_goal, dim=-1).cpu()
        )
        clearances.append(ball_clearance(frozen_ball).cpu())
    env.close()

    def shaped(values, tail=()):
        return torch.stack(values, dim=1).reshape(roots, count, horizon + 1, *tail)

    return {
        "return": total.cpu().reshape(roots, count),
        "block_reward": torch.stack(block_rewards, dim=1).reshape(roots, count, horizon),
        "collision": torch.stack(block_collisions, dim=1).reshape(roots, count, horizon),
        "live_start": torch.stack(live_starts, dim=1).reshape(roots, count, horizon),
        "observation": shaped(observations, frozen_obs.shape[1:]),
        "entities": shaped(entities, (frozen_entities.shape[-1],)),
        "ball_position": shaped(ball_positions, (2,)),
        "goal_position": shaped(goal_positions, (2,)),
        "distance": shaped(distances),
        "clearance": shaped(clearances),
    }


class DiagnosticHead(nn.Module):
    """Task-sufficient readout from a frozen global latent transition."""

    def __init__(self, input_dim, hidden_dim, mean, std):
        super().__init__()
        self.body = mlp(input_dim, hidden_dim, hidden_dim)
        self.regression = nn.Linear(hidden_dim, len(REGRESSION_NAMES))
        self.collision = nn.Linear(hidden_dim, 1)
        self.register_buffer("target_mean", mean.clone())
        self.register_buffer("target_std", std.clone())

    def forward(self, features):
        hidden = self.body(features)
        normalized = self.regression(hidden)
        return normalized * self.target_std + self.target_mean, self.collision(hidden).squeeze(-1)


def stack_dataset(dataset):
    return next(iter(DataLoader(dataset, batch_size=len(dataset), collate_fn=torch.stack)))


def diagnostic_targets(batch):
    agents = batch["agent_state"].shape[-2]
    ball = batch["package_state"][..., 0, :2]
    base_observation = batch["observation"][..., :6]
    goal = (
        batch["agent_state"][..., :2] - base_observation[..., 4:6]
    ).mean(dim=-2)
    distance = torch.linalg.vector_norm(ball - goal, dim=-1)
    progress = distance[:, :-1] - distance[:, 1:]
    rewards = block_reward(batch).sum(dim=(-2, -1))
    collision = (batch["primitive_reward"] < -1.0).any(dim=(2, 3, 4))
    collision_cost = (agents * progress - rewards).clamp_min(0)
    regression = torch.cat(
        [
            progress.unsqueeze(-1),
            ball_clearance(ball[:, 1:]).unsqueeze(-1),
            ball[:, 1:],
            collision_cost.unsqueeze(-1),
        ],
        dim=-1,
    )
    return regression, collision.float()


@torch.no_grad()
def diagnostic_features(model, batch, device, source):
    observation = batch["observation"].to(device)
    latent = model.encode(observation)
    if source == "true":
        following = latent[:, 1:]
    elif source == "predicted":
        following = model.predict(latent[:, :-1], batch["action"].to(device))
    else:
        raise ValueError("source must be true or predicted")
    pair = torch.cat([latent[:, :-1], following], dim=-1)
    return pair.flatten(2).detach()


def masked_mean(values, mask):
    selected = values[mask]
    if not selected.numel():
        raise ValueError("Empty diagnostic mask")
    return selected.mean()


def diagnostic_loss(head, features, targets, collision, valid, outcome, pos_weight):
    regression, logits = head(features)
    # Give every task quantity equal scale. In raw units the collision penalty
    # is orders of magnitude larger and would collapse this back into another
    # scalar reward regressor.
    normalized_error = (regression - targets) / head.target_std
    reg = masked_mean(
        normalized_error.square(), valid.unsqueeze(-1).expand_as(targets)
    )
    bce = torch.nn.functional.binary_cross_entropy_with_logits(
        logits[outcome], collision[outcome], pos_weight=pos_weight
    )
    return reg + bce, reg, bce


def fit_diagnostic_head(
    model, batches, device, source, seed=8200, epochs=300, patience=30
):
    features = {
        split: diagnostic_features(model, batch, device, source)
        for split, batch in batches.items()
    }
    targets = {split: diagnostic_targets(batch) for split, batch in batches.items()}
    train_target, train_collision = targets["train"]
    valid = batches["train"]["valid"]
    flat = train_target[valid]
    mean = flat.mean(dim=0).to(device)
    std = flat.std(dim=0).clamp_min(1e-4).to(device)
    torch.manual_seed(seed)
    head = DiagnosticHead(features["train"].shape[-1], 256, mean, std).to(device)
    # Predicted latents exist for partial terminal blocks, but their true
    # end-of-block counterparts do not exist in this dataset.
    collision_mask = "outcome_valid" if source == "predicted" else "valid"
    train_outcome = batches["train"][collision_mask]
    positives = train_collision[train_outcome].sum()
    negatives = train_outcome.sum() - positives
    pos_weight = (negatives / positives.clamp_min(1)).to(device)
    optimizer = torch.optim.AdamW(head.parameters(), lr=1e-3, weight_decay=1e-4)
    best, best_epoch, best_state, stale = float("inf"), -1, None, 0
    for epoch in range(epochs):
        head.train()
        optimizer.zero_grad(set_to_none=True)
        loss, _reg, _bce = diagnostic_loss(
            head,
            features["train"],
            train_target.to(device),
            train_collision.to(device),
            batches["train"]["valid"].to(device),
            train_outcome.to(device),
            pos_weight,
        )
        loss.backward()
        torch.nn.utils.clip_grad_norm_(head.parameters(), 1.0)
        optimizer.step()
        head.eval()
        with torch.no_grad():
            score = float(
                diagnostic_loss(
                    head,
                    features["validation"],
                    targets["validation"][0].to(device),
                    targets["validation"][1].to(device),
                    batches["validation"]["valid"].to(device),
                    batches["validation"][collision_mask].to(device),
                    pos_weight,
                )[0]
            )
        if score < best - 1e-5:
            best, best_epoch = score, epoch
            best_state = {name: value.detach().cpu().clone() for name, value in head.state_dict().items()}
            stale = 0
        else:
            stale += 1
            if stale >= patience:
                break
    if best_state is None:
        raise ValueError("Diagnostic head did not produce a finite checkpoint")
    head.load_state_dict(best_state)
    head.eval()
    return head, {
        "best_epoch": best_epoch,
        "validation_loss": best,
        "epochs": epoch + 1,
        "positive_examples": int(positives),
        "negative_examples": int(negatives),
    }


def binary_auc(score, target):
    positive = score[target.bool()]
    negative = score[~target.bool()]
    if not positive.numel() or not negative.numel():
        return None
    comparisons = (positive[:, None] > negative[None]).float()
    ties = (positive[:, None] == negative[None]).float() * 0.5
    return float((comparisons + ties).mean())


@torch.no_grad()
def diagnostic_test(head, model, batch, device, source):
    features = diagnostic_features(model, batch, device, source)
    target, collision = diagnostic_targets(batch)
    prediction, logits = head(features)
    valid = batch["valid"].to(device)
    outcome = batch[
        "outcome_valid" if source == "predicted" else "valid"
    ].to(device)
    result = {}
    for index, name in enumerate(REGRESSION_NAMES):
        mask = valid
        error = prediction[..., index][mask] - target[..., index].to(device)[mask]
        result[f"{name}_rmse"] = float(error.square().mean().sqrt())
        result[f"{name}_mae"] = float(error.abs().mean())
    probability = torch.sigmoid(logits[outcome]).cpu()
    labels = collision[outcome.cpu()]
    result["collision_brier"] = float((probability - labels).square().mean())
    result["collision_auc"] = binary_auc(probability, labels)
    result["collision_rate"] = float(labels.mean())
    return result


def blocked_actions(candidates, agents, action_block):
    batch, count, horizon, plan_dim = candidates.shape
    action_dim = plan_dim // (agents * action_block)
    return candidates.view(batch * count, horizon, agents, action_block * action_dim)


def reward_cost(model, sequence):
    reward, terminated = model.readout(sequence[:, :-1], sequence[:, 1:])
    alive = 1 - torch.sigmoid(terminated)
    survival = torch.cat(
        [torch.ones_like(alive[:, :1]), torch.cumprod(alive, dim=1)[:, :-1]], dim=1
    )
    return -(reward.squeeze(-1) * survival.unsqueeze(-1)).sum(dim=(1, 2))


def diagnostic_costs(head, sequence, goal):
    pair = torch.cat([sequence[:, :-1], sequence[:, 1:]], dim=-1).flatten(2)
    regression, logits = head(pair)
    probability = torch.sigmoid(logits)
    alive = 1 - probability
    survival = torch.cat(
        [torch.ones_like(alive[:, :1]), torch.cumprod(alive, dim=1)[:, :-1]], dim=1
    )
    progress = regression[..., 0]
    clearance = regression[..., 1]
    ball = regression[..., 2:4]
    collision_cost = regression[..., 4].clamp_min(0)
    agents = sequence.shape[-2]
    expected_collision = (20.0 * probability * survival).sum(dim=1)
    probability_cost = -(agents * progress * survival).sum(dim=1) + expected_collision
    penalty_cost = -(agents * progress * survival).sum(dim=1) + (
        collision_cost * survival
    ).sum(dim=1)
    any_collision = 1 - torch.prod(1 - probability, dim=1)
    return {
        "D_probability": probability_cost,
        "D_penalty": penalty_cost,
        "D_progress": -(progress * survival).sum(dim=1),
        "D_ball_goal": torch.linalg.vector_norm(ball[:, -1] - goal, dim=-1),
        "D_collision": any_collision,
        "D_clearance": -clearance.min(dim=1).values,
    }


@torch.no_grad()
def predicted_paths(model, head, observation, goal, candidates, action_block, device):
    batch, count = candidates.shape[:2]
    agents, obs_dim = observation.shape[1:]
    actions = blocked_actions(candidates, agents, action_block).to(device)
    start = observation[:, None].expand(batch, count, agents, obs_dim)
    start = start.reshape(batch * count, 1, agents, obs_dim).to(device)
    initial = model.encode(start)
    rolled = model.rollout(initial, actions)
    sequence = torch.cat([initial, rolled], dim=1)
    values = {"C_reward_predicted": reward_cost(model, sequence)}
    expanded_goal = goal[:, None].expand(batch, count, 2).reshape(batch * count, 2).to(device)
    values.update(diagnostic_costs(head, sequence, expanded_goal))
    return {name: value.reshape(batch, count).cpu() for name, value in values.items()}


@torch.no_grad()
def true_latent_paths(model, head, trace, state_input, history_frames, device):
    roots, count, frames, agents, _ = trace["observation"].shape
    observation = trace["observation"].reshape(roots * count, frames, agents, -1)
    entities = trace["entities"].reshape(roots * count, frames, -1)
    shaped = compose_frames(state_input, observation, entities, history_frames).to(device)
    sequence = model.encode(shaped)
    reward, terminated = model.readout(sequence[:, :-1], sequence[:, 1:])
    alive = 1 - torch.sigmoid(terminated)
    survival = torch.cat(
        [torch.ones_like(alive[:, :1]), torch.cumprod(alive, dim=1)[:, :-1]], dim=1
    )
    predicted_survival = -(reward.squeeze(-1) * survival.unsqueeze(-1)).sum(dim=(1, 2))
    true_live = trace["live_start"].reshape(roots * count, -1).to(device)
    true_survival = -(reward.squeeze(-1) * true_live.unsqueeze(-1)).sum(dim=(1, 2))
    goal = trace["goal_position"][:, :, 0].reshape(roots * count, 2).to(device)
    structured = diagnostic_costs(head, sequence, goal)
    result = {
        "B_reward_true_latent": predicted_survival,
        "B_reward_true_latent_true_mask": true_survival,
        **{f"T_{name}": value for name, value in structured.items()},
    }
    return {name: value.reshape(roots, count).cpu() for name, value in result.items()}


def percentile(values, index):
    return float((values < values[index]).float().mean())


def rank_metrics(predicted, trace, topk, named_candidates=False):
    true_cost = -trace["return"]
    roots, count = true_cost.shape
    per_root = []
    for root in range(roots):
        pred, truth = predicted[root], true_cost[root]
        selected = int(pred.argmin())
        true_top = set(torch.topk(truth, min(topk, count), largest=False).indices.tolist())
        pred_top = set(torch.topk(pred, min(topk, count), largest=False).indices.tolist())
        rho = spearman(pred, truth)
        row = {
            "spearman": rho,
            "topk_recall": len(true_top & pred_top) / len(true_top),
            "candidate0_percentile": percentile(pred, 0),
            "selected_regret": float(truth[selected] - truth.min()),
            "selected_return": float(trace["return"][root, selected]),
            "selected_distance": float(trace["distance"][root, selected, -1]),
            "selected_collision": bool(trace["collision"][root, selected].any()),
        }
        if named_candidates:
            row.update(
                {
                    "oracle_percentile": percentile(pred, 0),
                    "zero_percentile": percentile(pred, 1),
                    "oracle_predicted_cost": float(pred[0]),
                    "zero_predicted_cost": float(pred[1]),
                }
            )
        per_root.append(row)
    keys = per_root[0].keys()
    aggregate = {}
    for key in keys:
        values = [row[key] for row in per_root if row[key] is not None]
        if not values:
            aggregate[key] = None
        elif isinstance(values[0], bool):
            aggregate[key] = sum(values) / len(values)
        else:
            finite = [value for value in values if value == value]
            aggregate[key] = sum(finite) / len(finite) if finite else None
    aggregate["roots"] = roots
    aggregate["candidates"] = count
    aggregate["per_root"] = per_root
    return aggregate


def root_inputs(task, snapshot, device):
    roots = snapshot["steps"].shape[0]
    env = task.get_env_fun(roots, True, 0, device)()
    env.reset()
    restore_state(env, snapshot)
    observation = agent_observations(env).cpu()
    entities = entity_frame(env).cpu()
    goal = env._env.scenario.goal.state.pos.cpu()
    agents = len(env._env.world.agents)
    low, high = action_bounds(env)
    primitive = env.full_action_spec_unbatched["agents", "action"].shape[-1]
    env.close()
    return observation, entities, goal, agents, primitive, low, high


def build_bank(args):
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    manifest = yaml.safe_load((args.data / "manifest.json").read_text())
    task = VmasTask[manifest["task_name"].split("/")[-1].upper()].get_from_yaml()
    initial = torch.load(args.data / "initial_states.pt", map_location="cpu", weights_only=False)
    indices = torch.arange(args.roots)
    snapshot = take_snapshot(initial["snapshot"], indices, args.device)
    observation, entities, goal, agents, primitive, low, high = root_inputs(task, snapshot, args.device)
    block = manifest["action_block"]
    plan_dim = agents * primitive * block
    scratch = task.get_env_fun(args.roots * args.num_samples, True, 0, args.device)()
    scratch.reset()
    try:
        from examples.world_model.cost_landscape import true_scores

        def oracle_cost(candidates):
            total, _distance, _collision = true_scores(
                scratch, snapshot, unpack_actions(candidates, block), block,
                task_outcome(manifest["task_name"]),
            )
            return (-total).to(args.device)

        oracle = cem_plan(
            oracle_cost,
            action_dim=plan_dim,
            action_low=low,
            action_high=high,
            config=CEMConfig(
                horizon=args.horizon,
                num_samples=args.num_samples,
                num_elites=args.num_elites,
                num_iters=args.num_iters,
            ),
            batch_size=args.roots,
            device=args.device,
            generator=torch.Generator(device=args.device).manual_seed(args.seed),
        ).plan
    finally:
        scratch.close()
    generator = torch.Generator().manual_seed(args.seed + 1)
    random = torch.rand(
        args.roots, args.random_plans, args.horizon, plan_dim, generator=generator
    ) * (high - low) + low
    bank = torch.cat(
        [oracle.cpu().unsqueeze(1), torch.zeros(args.roots, 1, args.horizon, plan_dim), random],
        dim=1,
    )
    trace = rollout_truth(task, snapshot, bank, block, args.device)
    artifact = {
        "task_name": manifest["task_name"],
        "action_block": block,
        "seed": args.seed,
        "root_indices": indices,
        "snapshot": tree_map(snapshot, lambda value: value.cpu()),
        "root_observation": observation,
        "root_entities": entities,
        "root_goal": goal,
        "action_low": low,
        "action_high": high,
        "candidates": bank,
        "truth": trace,
    }
    torch.save(artifact, output / "candidate_bank.pt")
    summary = {
        "roots": args.roots,
        "candidates": bank.shape[1],
        "horizon": args.horizon,
        "oracle_return": float(trace["return"][:, 0].mean()),
        "zero_return": float(trace["return"][:, 1].mean()),
        "random_return": float(trace["return"][:, 2:].mean()),
        "oracle_distance": float(trace["distance"][:, 0, -1].mean()),
        "zero_distance": float(trace["distance"][:, 1, -1].mean()),
        "random_distance": float(trace["distance"][:, 2:, -1].mean()),
    }
    write_json(output / "bank_summary.json", summary)
    print(json.dumps(summary, indent=2), flush=True)


def checkpoint_rows(runs, state_input, regime, seed):
    rows = []
    for config_path in sorted(Path(runs).glob("[0-9]*/resolved_config.yaml")):
        config = yaml.safe_load(config_path.read_text())
        if (
            config["seed"] == seed
            and config["data"].get("state_input", "observation") == state_input
            and config["data"]["regime"] == regime
            and (config_path.parent / "model.pt").exists()
        ):
            rows.append((config_path.parent, config))
    by_kind = {config["model"]["kind"]: (path, config) for path, config in rows}
    if set(by_kind) != set(KINDS):
        raise ValueError(
            f"Expected checkpoints for {KINDS}, found {tuple(sorted(by_kind))}"
        )
    return [by_kind[kind] for kind in KINDS]


def data_batches(data, regime, state_input, block, history):
    return {
        split: stack_dataset(
            OfflineSequences(
                data, regime, split, action_block=block,
                state_input=state_input, history_frames=history,
            )
        )
        for split in ("train", "validation", "test")
    }


def evaluate_group(args):
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    bank = torch.load(args.bank, map_location="cpu", weights_only=False)
    manifest = yaml.safe_load((args.data / "manifest.json").read_text())
    task = VmasTask[manifest["task_name"].split("/")[-1].upper()].get_from_yaml()
    rows = checkpoint_rows(args.runs, args.state_input, args.regime, args.seed)
    if len(rows) != len(KINDS):
        raise ValueError(f"Expected three checkpoints, found {len(rows)}")
    history = rows[0][1]["data"].get("history_frames", 3)
    batches = data_batches(
        args.data, args.regime, args.state_input, bank["action_block"], history
    )
    root_observation = compose_frames(
        args.state_input,
        bank["root_observation"].unsqueeze(1),
        bank["root_entities"].unsqueeze(1),
        history,
    )[:, 0]
    snapshot = tree_map(bank["snapshot"], lambda value: value.to(args.device))
    records = []
    for index, (run, config) in enumerate(rows, 1):
        kind = config["model"]["kind"]
        print(f"[{index}/3] {args.state_input} {args.regime} {kind}", flush=True)
        model = load_model(run / "model.pt", args.device)
        predicted_head, predicted_fit = fit_diagnostic_head(
            model,
            batches,
            args.device,
            "predicted",
            epochs=args.head_epochs,
            patience=args.head_patience,
        )
        true_head, true_fit = fit_diagnostic_head(
            model,
            batches,
            args.device,
            "true",
            epochs=args.head_epochs,
            patience=args.head_patience,
        )
        head_test = {
            "predicted": diagnostic_test(
                predicted_head, model, batches["test"], args.device, "predicted"
            ),
            "true": diagnostic_test(
                true_head, model, batches["test"], args.device, "true"
            ),
        }
        fixed = {
            "A_true": -bank["truth"]["return"],
            **true_latent_paths(
                model, true_head, bank["truth"], args.state_input, history, args.device
            ),
            **predicted_paths(
                model,
                predicted_head,
                root_observation,
                bank["root_goal"],
                bank["candidates"],
                bank["action_block"],
                args.device,
            ),
        }
        fixed_metrics = {
            name: rank_metrics(
                cost, bank["truth"], args.topk, named_candidates=True
            )
            for name, cost in fixed.items()
        }

        stage_roots = min(args.stage_roots, bank["candidates"].shape[0])
        stage_observation = root_observation[:stage_roots]
        stage_goal = bank["root_goal"][:stage_roots]

        def planner_cost(candidates):
            return predicted_paths(
                model, predicted_head, stage_observation, stage_goal,
                candidates, bank["action_block"], args.device,
            )["C_reward_predicted"].to(args.device)

        cem = cem_plan(
            planner_cost,
            action_dim=bank["candidates"].shape[-1],
            action_low=bank["action_low"],
            action_high=bank["action_high"],
            config=CEMConfig(
                horizon=bank["candidates"].shape[-2],
                num_samples=args.num_samples,
                num_elites=args.num_elites,
                num_iters=args.num_iters,
            ),
            batch_size=stage_roots,
            device=args.device,
            generator=torch.Generator(device=args.device).manual_seed(args.cem_seed),
            record_candidates=True,
        )
        stage_snapshot = take_snapshot(
            snapshot, torch.arange(stage_roots, device=args.device), args.device
        )
        stages = []
        for iteration, candidates in enumerate(cem.candidate_history):
            truth = rollout_truth(
                task, stage_snapshot, candidates, bank["action_block"], args.device
            )
            paths = {
                "A_true": -truth["return"],
                **true_latent_paths(
                    model, true_head, truth, args.state_input, history, args.device
                ),
                **predicted_paths(
                    model, predicted_head, stage_observation, stage_goal,
                    candidates, bank["action_block"], args.device,
                ),
            }
            stages.append(
                {
                    "iteration": iteration,
                    "paths": {
                        name: rank_metrics(cost, truth, args.topk)
                        for name, cost in paths.items()
                    },
                }
            )
            print(f"  CEM stage {iteration + 1}/{args.num_iters}", flush=True)

        record = {
            "run": str(run),
            "state_input": args.state_input,
            "regime": args.regime,
            "kind": kind,
            "seed": args.seed,
            "diagnostic_fit": {"predicted": predicted_fit, "true": true_fit},
            "diagnostic_test": head_test,
            "fixed_bank": fixed_metrics,
            "cem_stages": stages,
        }
        records.append(record)
        torch.save(
            {
                "predicted_head": predicted_head.state_dict(),
                "true_head": true_head.state_dict(),
            },
            output / f"heads_{kind}.pt",
        )
        torch.save(fixed, output / f"fixed_scores_{kind}.pt")
        write_json(output / f"result_{kind}.json", record)
        del model, predicted_head, true_head, cem
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    write_json(
        output / "summary.json",
        {"state_input": args.state_input, "regime": args.regime, "records": records},
    )


def render_summary(records, table, output):
    """Render the fixed-bank, CEM-stage, and head-quality diagnostics."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    colors = {
        "observation": "#4477AA",
        "history": "#EE6677",
        "physical": "#228833",
    }
    labels = {
        "A_true": "A truth",
        "B_reward_true_latent": "B true latent\n+ reward",
        "C_reward_predicted": "C rollout\n+ reward",
        "D_probability": "D rollout\n+ structured",
        "T_D_probability": "D true latent\n+ structured",
    }
    primary = [path for path in labels if path in records[0]["fixed_bank"]]
    lookup = {(row["state_input"], row["path"]): row for row in table}

    fig, axes = plt.subplots(2, 2, figsize=(13, 8), constrained_layout=True)
    metrics = (
        ("spearman", "Plan–Real Spearman", (-0.25, 1.05)),
        ("topk_recall", "Top-30 recall", (0, 1.05)),
        ("oracle_percentile", "Oracle percentile (lower is better)", (0, 1.05)),
        ("selected_regret", "Selected-plan regret (lower is better)", None),
    )
    width = 0.24
    x = torch.arange(len(primary)).numpy()
    for axis, (metric, title, limits) in zip(axes.flat, metrics):
        for offset, state_input in enumerate(INPUTS):
            values = [lookup[state_input, path][metric] for path in primary]
            axis.bar(
                x + (offset - 1) * width,
                [float("nan") if value is None else value for value in values],
                width,
                label=state_input,
                color=colors[state_input],
            )
        axis.set_title(title)
        axis.set_xticks(x, [labels[path] for path in primary])
        axis.grid(axis="y", alpha=0.25)
        if limits is not None:
            axis.set_ylim(*limits)
    axes[0, 0].legend(frameon=False, ncol=3)
    fig.suptitle("Gate 0d — where decision information disappears", fontsize=15)
    fig.savefig(output / "fixed_bank_paths.png", dpi=180)
    fig.savefig(output / "fixed_bank_paths.pdf")
    plt.close(fig)

    stage_paths = [
        path
        for path in ("B_reward_true_latent", "C_reward_predicted", "D_probability")
        if path in records[0]["cem_stages"][0]["paths"]
    ]
    fig, axes = plt.subplots(1, len(stage_paths), figsize=(5 * len(stage_paths), 4), constrained_layout=True)
    if len(stage_paths) == 1:
        axes = [axes]
    for axis, path in zip(axes, stage_paths):
        for state_input in INPUTS:
            selected = [row for row in records if row["state_input"] == state_input]
            iterations = len(selected[0]["cem_stages"])
            means = []
            for iteration in range(iterations):
                values = [
                    row["cem_stages"][iteration]["paths"][path]["spearman"]
                    for row in selected
                ]
                finite = [value for value in values if value is not None]
                means.append(sum(finite) / len(finite) if finite else float("nan"))
            axis.plot(
                range(1, iterations + 1),
                means,
                label=state_input,
                color=colors[state_input],
                linewidth=2,
            )
        axis.axhline(0, color="black", linewidth=0.8, alpha=0.5)
        axis.set_title(labels[path].replace("\n", " "))
        axis.set_xlabel("CEM iteration")
        axis.set_ylabel("Plan–Real Spearman")
        axis.grid(alpha=0.25)
    axes[0].legend(frameon=False)
    fig.suptitle("Rank alignment on the populations CEM actually visits", fontsize=14)
    fig.savefig(output / "cem_stage_spearman.png", dpi=180)
    fig.savefig(output / "cem_stage_spearman.pdf")
    plt.close(fig)

    probe_metrics = (
        ("progress_rmse", "Progress RMSE"),
        ("ball_clearance_rmse", "Wire-clearance RMSE"),
        ("collision_auc", "Collision AUROC"),
    )
    fig, axes = plt.subplots(1, 3, figsize=(13, 4), constrained_layout=True)
    for axis, (metric, title) in zip(axes, probe_metrics):
        for offset, state_input in enumerate(INPUTS):
            selected = [row for row in records if row["state_input"] == state_input]
            values = [row["diagnostic_test"]["predicted"][metric] for row in selected]
            finite = [value for value in values if value is not None]
            height = sum(finite) / len(finite) if finite else float("nan")
            axis.bar(offset, height, color=colors[state_input])
        axis.set_xticks(range(3), INPUTS, rotation=20)
        axis.set_title(title)
        axis.grid(axis="y", alpha=0.25)
    fig.suptitle("Task information decoded from predicted latents", fontsize=14)
    fig.savefig(output / "diagnostic_heads.png", dpi=180)
    fig.savefig(output / "diagnostic_heads.pdf")
    plt.close(fig)


def merge(args):
    records = []
    for path in args.summaries:
        records.extend(json.loads(Path(path).read_text())["records"])
    if len(records) != 18:
        raise ValueError(f"Expected 18 records, found {len(records)}")
    paths = sorted(records[0]["fixed_bank"])

    def average(rows, key):
        values = [row[key] for row in rows if row.get(key) is not None]
        return sum(values) / len(values) if values else None

    table = []
    for state_input in INPUTS:
        for path in paths:
            selected = [r["fixed_bank"][path] for r in records if r["state_input"] == state_input]
            table.append(
                {
                    "state_input": state_input,
                    "path": path,
                    "spearman": average(selected, "spearman"),
                    "topk_recall": average(selected, "topk_recall"),
                    "oracle_percentile": average(selected, "oracle_percentile"),
                    "selected_regret": average(selected, "selected_regret"),
                }
            )
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    write_json(output / "aggregate.json", {"records": records, "fixed_bank_table": table})
    render_summary(records, table, output)
    header = f"{'input':12s} {'path':36s} {'rho':>8s} {'topk':>8s} {'oracle%':>9s} {'regret':>9s}"
    print(header)
    print("-" * len(header))
    for row in table:
        shown = {
            key: "     n/a" if row[key] is None else f"{row[key]:8.4f}"
            for key in ("spearman", "topk_recall", "oracle_percentile", "selected_regret")
        }
        print(
            f"{row['state_input']:12s} {row['path']:36s} {shown['spearman']} "
            f"{shown['topk_recall']} {shown['oracle_percentile']:>9s} "
            f"{shown['selected_regret']:>9s}"
        )


def build_parser():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="command", required=True)
    bank = sub.add_parser("build-bank")
    bank.add_argument("--data", type=Path, required=True)
    bank.add_argument("--output", type=Path, required=True)
    bank.add_argument("--roots", type=int, default=16)
    bank.add_argument("--random-plans", type=int, default=300)
    bank.add_argument("--horizon", type=int, default=5)
    bank.add_argument("--num-samples", type=int, default=300)
    bank.add_argument("--num-elites", type=int, default=30)
    bank.add_argument("--num-iters", type=int, default=30)
    bank.add_argument("--seed", type=int, default=7100)
    bank.add_argument("--device", default="cuda")

    evaluate = sub.add_parser("evaluate")
    evaluate.add_argument("runs", type=Path)
    evaluate.add_argument("--data", type=Path, required=True)
    evaluate.add_argument("--bank", type=Path, required=True)
    evaluate.add_argument("--output", type=Path, required=True)
    evaluate.add_argument("--state-input", choices=INPUTS, required=True)
    evaluate.add_argument("--regime", choices=REGIMES, required=True)
    evaluate.add_argument("--seed", type=int, default=4100)
    evaluate.add_argument("--topk", type=int, default=30)
    evaluate.add_argument("--stage-roots", type=int, default=8)
    evaluate.add_argument("--num-samples", type=int, default=300)
    evaluate.add_argument("--num-elites", type=int, default=30)
    evaluate.add_argument("--num-iters", type=int, default=30)
    evaluate.add_argument("--cem-seed", type=int, default=7300)
    evaluate.add_argument("--head-epochs", type=int, default=300)
    evaluate.add_argument("--head-patience", type=int, default=30)
    evaluate.add_argument("--device", default="cuda")

    aggregate = sub.add_parser("merge")
    aggregate.add_argument("summaries", nargs="+", type=Path)
    aggregate.add_argument("--output", type=Path, required=True)
    return ap


def main():
    args = build_parser().parse_args()
    if args.command == "build-bank":
        build_bank(args)
    elif args.command == "evaluate":
        evaluate_group(args)
    else:
        merge(args)


if __name__ == "__main__":
    main()
